" vim: set sw=2 ts=2 sts=2 et tw=78 foldmarker={,} foldlevel=0 foldmethod=marker:
scriptencoding utf-8

" Environment {
    " let g:python3_host_prog = '~/nvim_venv/bin/python'

    " Identify platform {
        silent function! OSX()
            return has('macunix')
        endfunction

        silent function! LINUX()
            return has('unix') && !has('macunix') && !has('win32unix')
        endfunction

        silent function! WINDOWS()
            return  (has('win32') || has('win64'))
        endfunction
    " }
" }

" Vim-plug {
    if filereadable(expand('~/.config/nvim/vimrc.plugins'))
        source ~/.config/nvim/vimrc.plugins
    endif
" }

" Custom method {
    if filereadable(expand('~/.config/nvim/vimrc.conf'))
        source ~/.config/nvim/vimrc.conf
    endif
" }

" Custom method {
    if filereadable(expand('~/.config/nvim/vimrc.maps'))
        source ~/.config/nvim/vimrc.maps
    endif
" }

" Custom method {
    if filereadable(expand('~/.config/nvim/vimrc.custom'))
        source ~/.config/nvim/vimrc.custom
    endif
" }
